import Head from "next/head";
import styles from "../styles/Home.module.css";
import Hero from "../components/Hero";
import Stats from "../components/Stats";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <Stats />
      </main>
    </div>
  );
}

// useEffect(() => {
//   const options = {
//     method: "GET",
//     url: "https://coingecko.p.rapidapi.com/global",
//     headers: {
//       "x-rapidapi-host": "coingecko.p.rapidapi.com",
//       "x-rapidapi-key": "eb6d684b20mshd3b4025d7c50329p141521jsn8cb44c488bff",
//     },
//   };

//   axios
//     .request(options)
//     .then(function (response) {
//       console.log(response.data.data.active_cryptocurrencies);
//     })
//     .catch(function (error) {
//       console.error(error);
//     });
// }, []);
