import Head from "next/head";
import styles from "../styles/Home.module.css";
import Hero from "../components/Hero";
import GlobalData from "../components/GlobalData";
import Stats from "../components/Stats";
import News from "../components/News";
import Exchanges from "../components/Exchanges";
import Loading from "../components/Loading";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <GlobalData />
        <Stats />

        <Exchanges />
        <News /> 
      </main>
    </div>
  );
}
